FROM python:3.8
LABEL maintainer="223689@supinfo.com"
COPY . .
RUN apt-get update -y && apt-get install python-dev python3-dev libsasl2-dev python-dev libldap2-dev libssl-dev -y
RUN pip install flask flask_httpauth flask_simpleldap python-dotenv
CMD [ "python", "student_age.py" ]