FROM python:2.7-stretch
LABEL maintainer="223689@supinfo.com"
COPY ./simple_api/student_age_test.py /
COPY ./simple_api/student_age.json /
COPY ./simple_api/student_age.py /
RUN apt-get update -y && apt-get install python-dev python3-dev libsasl2-dev python-dev libldap2-dev libssl-dev -y
RUN pip install flask flask_httpauth flask_simpleldap python-dotenv
RUN python ./student_age_test.py