---
- name: Install Docker and init Gitlab CE
  hosts: localhost
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install prerequisites for Docker repository
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Update apt and install docker-ce-cli
      apt: update_cache=yes name=docker-ce-cli state=latest

    - name: Update apt and install containerd.io
      apt: update_cache=yes name=containerd.io state=latest

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Pull the image runner
      docker_image:
        name: "{{ runner_container_image }}"
        source: pull

    - name: Create the runner containers
      docker_container:
        name: "{{ runner_container_name }}"
        image: "{{ runner_container_image }}"
        state: present
